# Tag Normalization Configuration

# Use Underscores: Determines whether to use underscores or spaces in output tags
# Default: false (use spaces)
use_underscores = false

# Keep Implied: Whether to keep implied tags or remove them. Can also be a list of tags
# Default: false (remove implied tags)
keep_implied = false

# Artist By Prefix: Whether to add "by_" prefix to artist tags
# Default: true
artist_by_prefix = true

# Blacklist: A list of tags to be removed during normalization
# These tags will be completely excluded from the output
# Default: ["invalid tag"]
blacklist = [
    "invalid tag",
    "by conditional dnp",
    "hi res",
    "absurd res",
    "superabsurd res",
    "4k",
    "uncensored",
    "ambiguous gender",
    "translation edit",
    "story in description",
    "non- balls",
    "non- nipples",
    "non- breasts",
    "feet out of frame",
    "funny_post_number",
    "tagme",
    "edit_request",
]

# Blacklist Regular Expressions: Tags matching these regexes will be removed
# These are full-match regexes, so they must match the entire tag
blacklist_regexp = [
    "(\\d+s?|\\d+:\\d+)", # Numbers, years and aspect ratio
    ".*?_at_source",
]

# Blacklist Implied: Whether to also blacklist tags implied by blacklisted tags
# Default: true
blacklist_implied = true

# Blacklist Categories: Entire categories of tags to be removed
# Common categories include "artist", "character", "copyright", "general", "meta", "species", "pool"
blacklist_categories = ["pool"]

# Keep Underscores: List of tags where underscores should be preserved
# By default, underscores are replaced with spaces unless specified here
keep_underscores = ["rating_explicit", "rating_questionable", "rating_safe"]

# Remove Parentheses Suffix: Categories where parenthetical suffixes should be removed
# E.g., "character_(series)" becomes just "character" if does not conflicts with
# an existing tag/alias (for on_alias_conflict="ignore")
remove_parens_suffix_for_categories = [
    "artist",
    "character",
    "copyright",
    "lore",
    "species",
]

# On Alias Conflict: How to handle conflicts when creating aliases
# Options: "silent", "overwrite", "overwrite_rarest", "warn", "raise"
# Default: "ignore" meaning do not modify the alias
on_alias_conflict = "ignore"

# Aliases: Define tag aliases (alternative names for the same tag)
# The key is the alias, and the value is the target tag
[aliases]
explicit = "rating_explicit"
score_explicit = "rating_explicit"
score_safe = "rating_safe"
score_questionable = "rating_questionable"

# Aliases Overrides: Similar to aliases, but can override existing tag meanings
# Use this carefully as it can change the semantics of existing tags
[aliases_overrides]
safe = "rating_safe"
questionable = "rating_questionable"

# Renames: Specify tags to be renamed in the output
# This also causes them to be recognized as aliases in the input (for idempotency)
# The key is the original tag name, and the value is the new name
[renames]
domestic_cat = "cat"
domestic_dog = "dog"
